// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCJ1GwnZSv_2sT3q5MB6pUQxEx7SS1F5aY',
    appId: '1:290026814616:web:2842abc0a446dcf61024ed',
    messagingSenderId: '290026814616',
    projectId: 'glitchxapp00711',
    authDomain: 'glitchxapp00711.firebaseapp.com',
    storageBucket: 'glitchxapp00711.firebasestorage.app',
    measurementId: 'G-MR0477639L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAfuGnOYOC-rHK2xxwPiWWEcMhKyiMPQPY',
    appId: '1:290026814616:android:1f6903683346a26f1024ed',
    messagingSenderId: '290026814616',
    projectId: 'glitchxapp00711',
    storageBucket: 'glitchxapp00711.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDH29yjJdWoCa-xivdYRjKEk6g7dOJ1yOQ',
    appId: '1:290026814616:ios:926b3210e50045b41024ed',
    messagingSenderId: '290026814616',
    projectId: 'glitchxapp00711',
    storageBucket: 'glitchxapp00711.firebasestorage.app',
    androidClientId: '290026814616-3av9mjesj3qopfod3lq9pl75ntp01mm7.apps.googleusercontent.com',
    iosClientId: '290026814616-q574hj5p2argbbaq8atvt0gbugq415ei.apps.googleusercontent.com',
    iosBundleId: 'com.example.glitchxAdmin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDH29yjJdWoCa-xivdYRjKEk6g7dOJ1yOQ',
    appId: '1:290026814616:ios:926b3210e50045b41024ed',
    messagingSenderId: '290026814616',
    projectId: 'glitchxapp00711',
    storageBucket: 'glitchxapp00711.firebasestorage.app',
    androidClientId: '290026814616-3av9mjesj3qopfod3lq9pl75ntp01mm7.apps.googleusercontent.com',
    iosClientId: '290026814616-q574hj5p2argbbaq8atvt0gbugq415ei.apps.googleusercontent.com',
    iosBundleId: 'com.example.glitchxAdmin',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCJ1GwnZSv_2sT3q5MB6pUQxEx7SS1F5aY',
    appId: '1:290026814616:web:2842abc0a446dcf61024ed',
    messagingSenderId: '290026814616',
    projectId: 'glitchxapp00711',
    authDomain: 'glitchxapp00711.firebaseapp.com',
    storageBucket: 'glitchxapp00711.firebasestorage.app',
    measurementId: 'G-MR0477639L',
  );

}